import os

MAX_X = 800
MAX_Y = 600
CENTER_X = MAX_X / 2
CENTER_Y = MAX_Y / 2
A_HAND_Y = CENTER_Y + 100
B_HAND_Y = CENTER_Y - 100
LEFT_A_HAND_X_MAX = 600
LEFT_A_HAND_X_MIN = 0
LEFT_B_HAND_X_MAX = 200
LEFT_B_HAND_X_MIN = 0
RIGHT_A_HAND_X_MAX = MAX_X
RIGHT_B_HAND_X_MIN = MAX_X - 200
RIGHT_A_HAND_X_MAX = MAX_X
RIGHT_B_HAND_X_MIN = MAX_X - 600

SLAP_SPEED = 60

LEFT_FACING_A_IMAGE = "images/left_facing_a.png"
LEFT_FACING_B_IMAGE = "images/left_facing_b.png"
RIGHT_FACING_A_IMAGE = "images/right_facing_a.png"
RIGHT_FACING_B_IMAGE = "images/right_facing_b.png"